ansible_network_os: ios
ansible_connection: network_cli
ansible_user: controler
ansible_password: C0nTroll3r124#@
ansible_become_password: C0nTroll3r124#@
ansible_become: yes
ansible_become_method: enable
